In [1]:
"""Replace NaN with 0 and Interchange Rows & Columns"""


import numpy as np

arr = np.array([[6, -8, 73, -110],
                [np.nan, -8, 0, 94]])

print("Original Array:")
print(arr)

# Replace NaN with 0
arr = np.nan_to_num(arr, nan=0)

print("\nAfter Replacing NaN with 0:")
print(arr)

# Interchange rows and columns (Transpose)
transposed = arr.T

print("\nAfter Interchanging Rows and Columns:")
print(transposed)

Original Array:
[[   6.   -8.   73. -110.]
 [  nan   -8.    0.   94.]]

After Replacing NaN with 0:
[[   6.   -8.   73. -110.]
 [   0.   -8.    0.   94.]]

After Interchanging Rows and Columns:
[[   6.    0.]
 [  -8.   -8.]
 [  73.    0.]
 [-110.   94.]]


In [2]:
"""Move Axes of 3D Array to New Positions"""
import numpy as np

arr = np.arange(24).reshape(2, 3, 4)

print("Original Shape:", arr.shape)

new_arr = np.moveaxis(arr, 0, 2)

print("New Shape:", new_arr.shape)
print(new_arr)

Original Shape: (2, 3, 4)
New Shape: (3, 4, 2)
[[[ 0 12]
  [ 1 13]
  [ 2 14]
  [ 3 15]]

 [[ 4 16]
  [ 5 17]
  [ 6 18]
  [ 7 19]]

 [[ 8 20]
  [ 9 21]
  [10 22]
  [11 23]]]


In [3]:
"""Replace NaN Values with Average of Columns"""
import numpy as np

arr = np.array([[10, np.nan, 30],
                [20, 25, np.nan],
                [30, 35, 40]])

print("Original Array:")
print(arr)

# Column averages ignoring NaN
col_mean = np.nanmean(arr, axis=0)

# Find NaN positions
inds = np.where(np.isnan(arr))

# Replace NaN with column mean
arr[inds] = np.take(col_mean, inds[1])

print("\nArray after replacing NaN with Column Average:")
print(arr)

Original Array:
[[10. nan 30.]
 [20. 25. nan]
 [30. 35. 40.]]

Array after replacing NaN with Column Average:
[[10. 30. 30.]
 [20. 25. 35.]
 [30. 35. 40.]]


In [4]:
"""Replace Negative Values with Zero"""
import numpy as np

arr = np.array([6, -8, 73, -110, 25, -5])

print("Original Array:")
print(arr)

arr = np.where(arr < 0, 0, arr)

print("\nAfter Replacing Negative Values with Zero:")
print(arr)

Original Array:
[   6   -8   73 -110   25   -5]

After Replacing Negative Values with Zero:
[ 6  0 73  0 25  0]
